ARG DEBIAN_IMAGE=debian:stable-slim
ARG BASE=gcr.io/distroless/static-debian12:nonroot
FROM golang:1.24 as coredns-builder
COPY . /go/src/github.com/coredns/coredns
WORKDIR /go/src/github.com/coredns/coredns
RUN go build -o coredns  .

FROM  ${DEBIAN_IMAGE} AS build
SHELL [ "/bin/sh", "-ec" ]

RUN export DEBCONF_NONINTERACTIVE_SEEN=true \
           DEBIAN_FRONTEND=noninteractive \
           DEBIAN_PRIORITY=critical \
           TERM=linux ; \
    apt-get -qq update ; \
    apt-get -yyqq upgrade ; \
    apt-get -yyqq install ca-certificates libcap2-bin; \
    apt-get clean
COPY --from=coredns-builder /go/src/github.com/coredns/coredns/coredns /coredns
RUN setcap cap_net_bind_service=+ep /coredns

FROM  ${DEBIAN_IMAGE}
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /coredns /coredns
WORKDIR /
EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]
